version: '3.8'
services:
  forward-proxy:
    build: .
    container_name: forward-proxy
    ports:
      - 3128:3128
    restart: unless-stopped
    network_mode: "bridge"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      PROXY_USER: admin
      PROXY_PASS: qwerty12345
      PROXY_UPSTREAM_URL: http://[3b67:145:324:7::5]:3128
